---
  - name: Main | Install Jenkins
    include: "jenkins.yml"
    tags: jenkins

  - name: Main | Install plugins
    include: "plugins.yml"
    tags: plugins

  - name: Main | Configure users
    include: "users.yml"
    tags: users
    when: jenkins_users is defined

  - name: Main | Setup Nginx proxy
    include: "nginx_proxy.yml"
    tags: nginx
    when: setup_nginx_secure_site

  - name: Main | Install Web Driver
    include: "webdriver.yml"
    tags: webdriver
    when: install-webdriver

  - name: Main | Install Prudentia/Ansible
    include: "prudentia.yml"
    tags: prudentia
    when: install-prudentia
