---
  # Parameters:
  #  prudentia_version (provided)

  - name: Prudentia | Install deps
    apt: pkg={{item}} state=present
    with_items:
      - libffi-dev
      - libssl-dev
    when: ansible_os_family == "Debian"
    become: yes

  - name: Prudentia | Install
    pip: name=prudentia version={{prudentia_version}}
    become: yes
